version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: exchange_demo
      POSTGRES_USER: exchange
      POSTGRES_PASSWORD: exchange
    ports:
      - "65432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  kafka:
    image: bitnami/kafka:3.7
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"

  notification-service-java:
    build:
      context: ..
      dockerfile: services/notification-service-java/Dockerfile
    environment:
      SERVER_PORT: 8094
      EXCHANGE_NOTIFICATION_GRPC_PORT: 10084
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      PRIVATE_EVENT_TOPIC: exchange.private.events
      WS_PREFIX: /topic/private
    depends_on:
      - kafka
    ports:
      - "8094:8094"
      - "10084:10084"

  market-data-service-java:
    build:
      context: ..
      dockerfile: services/market-data-service-java/Dockerfile
    environment:
      SERVER_PORT: 8095
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      EXCHANGE_MARKET_DATA_REDIS_ENABLED: "true"
      MARKET_DATA_REDIS_CHANNEL: exchange.market-data.snapshots
      MARKET_DATA_STREAM_PREFIX: /api/v1/market-data/stream
    depends_on:
      - redis
    ports:
      - "8095:8095"
